/**
 * types/api.ts
 * Canonical TypeScript types that mirror the shapes returned by every
 * /api/* route.  Client-side hooks, components, and the study session all
 * import from here — never from raw DB row types.
 *
 * Legacy types (Box, Card with `question`/`answer`) still live in
 * types/flashcard.ts for the Vite-era components.  Once TASK-006 (Frontend)
 * migrates every component, types/flashcard.ts will be deleted.
 */

// ── Subjects ──────────────────────────────────────────────────────────────────

export type Subject =
  | 'medicine' | 'pharmacy' | 'chemistry'
  | 'languages' | 'law' | 'science' | 'history' | 'mathematics' | 'computer_science'
  | 'other';

// ── Deck (/api/decks) ─────────────────────────────────────────────────────────

export interface Deck {
  id: string;
  userId: string;
  title: string;
  description: string;
  color: string;   // palette key: 'indigo' | 'emerald' | 'amber' | 'rose' | 'sky'
  emoji: string;   // single emoji character, e.g. '📚'
  isPublic: boolean;
  slug: string | null;
  subject: Subject | null;
  cardCount: number;
  createdAt: string;
  updatedAt: string;
}

// ── Public Deck (/api/explore) ────────────────────────────────────────────────

/**
 * A deck visible in the Explore feed. Extends Deck with creator info.
 * Returned by GET /api/explore and GET /api/explore/categories.
 */
export interface PublicDeck extends Omit<Deck, 'slug'> {
  slug: string;               // guaranteed non-null for public decks
  creatorName: string;        // display name of the deck author
  creatorUsername?: string | null;
  alreadyCopied: boolean;     // true when the authenticated user already has a copy
  copyCount?: number;         // denormalised copy count (explore feed + deck page)
  isVerifiedCreator?: boolean; // verified badge shown next to creator name
  deckType?: 'flashcard' | 'quiz';
}

/**
 * A subject category hub — returned by GET /api/explore/categories.
 */
export interface ExploreCategory {
  subject: Subject;
  label: string;
  description: string;
  color: string;   // Tailwind gradient class string
  emoji: string;
  deckCount: number;
}

// ── Quiz Deck ─────────────────────────────────────────────────────────────────

export interface QuizDeck {
  id: string;
  userId: string;
  title: string;
  description: string;
  color: string;
  emoji: string;
  isPublic: boolean;
  slug: string | null;
  subject: Subject | null;
  questionCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface QuizQuestion {
  id: string;
  quizDeckId: string;
  userId: string;
  questionText: string;
  correctAnswer: string;
  optionA: string;
  optionB: string;
  explanation: string | null;
  aiGenerated: boolean;
  srs?: {
    interval: number;
    easeFactor: number;
    dueDate: string | null;
    reviewCount: number;
  } | null;
  createdAt: string;
}

// ── SRS state (embedded in CardWithSrs) ───────────────────────────────────────

export type Grade = 'again' | 'hard' | 'good' | 'easy';

export interface SrsState {
  /** Next review interval in days. */
  interval: number;
  /** SM-2 ease factor — controls how fast the interval grows. Default 2.5. */
  easeFactor: number;
  /** ISO timestamp of the next due date. */
  dueDate: string;
  /** Total successful review streak (resets to 0 on "again"). */
  reviewCount: number;
  /** Most recent grade, or null if the card has never been reviewed. */
  lastGrade: Grade | null;
  /** ISO timestamp of the last review, or null if never reviewed. */
  lastReviewedAt: string | null;
}

// ── Card (/api/cards, /api/decks/[id]/cards) ──────────────────────────────────

export interface ApiCard {
  id: string;
  deckId: string;
  userId: string;
  front: string;
  back: string;
  frontImageUrl: string | null;
  backImageUrl: string | null;
  /** True while the card was generated by AI and has not been edited by the user. */
  aiGenerated: boolean;
  createdAt: string;
  updatedAt: string;
  /**
   * SRS state for the requesting user.
   * Always present on cards fetched via /api/decks/[id]/cards.
   * May be absent on cards fetched via /api/cards (CRUD only).
   */
  srs?: SrsState;
}

// ── Study session (/api/study/*) ──────────────────────────────────────────────

/**
 * Hypothetical next intervals for all four grade buttons.
 * Returned by both /api/study/session (per card) and /api/study/grade.
 * Used by the UI to label buttons: "Good → 4d", "Easy → 9d", etc.
 */
export interface IntervalPreview {
  again: number;
  hard: number;
  good: number;
  easy: number;
}

/** A card in the study session queue — includes SRS state and preview intervals. */
export interface StudyCard extends ApiCard {
  srs: SrsState; // guaranteed non-optional in session context
  preview: IntervalPreview;
}

/** Response shape from GET /api/study/session */
export interface StudySessionResponse {
  cards: StudyCard[];
  /** Total due (including cards not returned in catch-up mode). */
  totalDue: number;
  /** True when the session was capped by the catch-up algorithm. */
  isCatchup: boolean;
}

/** Request body for POST /api/study/grade */
export interface GradeRequest {
  cardId: string;
  grade: Grade;
}

/** Response shape from POST /api/study/grade */
export interface GradeResponse {
  cardId: string;
  grade: Grade;
  newInterval: number;
  newEaseFactor: number;
  newDueDate: string;
  newReviewCount: number;
  /** Updated preview intervals based on the new SRS state. */
  preview: IntervalPreview;
}
