-- ============================================================
-- FlashCard App — Initial PostgreSQL Schema
-- Migration: 001_initial_schema.sql
-- Date: 2026-04-12
-- Author: [BACKEND]
-- ============================================================

-- Enable UUID generation (required for gen_random_uuid())
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -------------------------------------------------------
-- TABLE: users
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  name           TEXT         NOT NULL,
  email          TEXT         UNIQUE NOT NULL,
  password_hash  TEXT         NOT NULL,
  is_pro         BOOLEAN      NOT NULL DEFAULT false,

  -- Subject preference for domain-aware AI prompts (Phase 3)
  subject        TEXT         CHECK (subject IN ('medicine', 'pharmacy', 'chemistry', 'other')),

  -- COPPA compliance gate (under-13 flag) — required by TASK-005
  coppa_verified BOOLEAN      NOT NULL DEFAULT false,

  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------
-- TABLE: decks
-- Client-side legacy name: "boxes". Renamed to "decks" server-side.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS decks (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       TEXT         NOT NULL,
  description TEXT         NOT NULL DEFAULT '',

  -- Public sharing (Phase 2 Explore page)
  is_public   BOOLEAN      NOT NULL DEFAULT false,
  slug        TEXT         UNIQUE,  -- Set when deck is made public, e.g. "usmle-cardiology-2026"

  -- Subject tag for Explore category hubs
  subject     TEXT         CHECK (subject IN ('medicine', 'pharmacy', 'chemistry', 'other')),

  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------
-- TABLE: cards
-- Supports separate front/back images for Phase 3 AI generation.
-- user_id is denormalized for fast per-user queries + clean GDPR cascade.
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS cards (
  id              UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  deck_id         UUID         NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
  user_id         UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  front           TEXT         NOT NULL,   -- question / prompt
  back            TEXT         NOT NULL,   -- answer / reveal

  front_image_url TEXT         DEFAULT NULL,
  back_image_url  TEXT         DEFAULT NULL,

  -- Flagged when generated by AI (Phase 3). Disclaimer shown in UI until user edits.
  ai_generated    BOOLEAN      NOT NULL DEFAULT false,

  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------
-- TABLE: srs_state
-- One row per (card × user) pair. Populated lazily on first review.
-- Cards with no srs_state row are treated as "new" (due immediately).
-- Designed to support both SM-2 and FSRS algorithms (TASK-004).
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS srs_state (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  card_id          UUID         NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  user_id          UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- SM-2 / FSRS core fields
  interval         INTEGER      NOT NULL DEFAULT 1,    -- days until next review
  ease_factor      FLOAT        NOT NULL DEFAULT 2.5,  -- SM-2: 1.3–2.5, FSRS: stability
  due_date         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  review_count     INTEGER      NOT NULL DEFAULT 0,

  -- Last rating: maps to FSRS grades (Again=1, Hard=2, Good=3, Easy=4)
  last_grade       TEXT         CHECK (last_grade IN ('again', 'hard', 'good', 'easy')),
  last_reviewed_at TIMESTAMPTZ  DEFAULT NULL,

  -- Enforce one SRS state row per card per user
  UNIQUE (card_id, user_id)
);

-- -------------------------------------------------------
-- TABLE: ai_usage
-- Tracks AI card generation per user per calendar month.
-- Enforces configurable free-tier limit (env: AI_FREE_CARDS_PER_MONTH, default 50).
-- UPSERT pattern: INSERT ... ON CONFLICT (user_id, month) DO UPDATE SET cards_generated = ...
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_usage (
  id              UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID     NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  month           TEXT     NOT NULL,   -- format: YYYY-MM (e.g. '2026-04')
  cards_generated INTEGER  NOT NULL DEFAULT 0,

  UNIQUE (user_id, month)
);

-- ============================================================
-- INDEXES
-- ============================================================

-- users: unique email lookups on login/register
CREATE INDEX IF NOT EXISTS idx_users_email
  ON users (email);

-- decks: list all decks by owner (dashboard)
CREATE INDEX IF NOT EXISTS idx_decks_user_id
  ON decks (user_id);

-- decks: slug lookup for public deck URLs (/explore/[subject]/[slug])
CREATE INDEX IF NOT EXISTS idx_decks_slug
  ON decks (slug)
  WHERE slug IS NOT NULL;

-- decks: Explore feed — only public decks
CREATE INDEX IF NOT EXISTS idx_decks_is_public
  ON decks (is_public)
  WHERE is_public = true;

-- decks: category hub filtering by subject
CREATE INDEX IF NOT EXISTS idx_decks_subject
  ON decks (subject)
  WHERE subject IS NOT NULL;

-- cards: list all cards in a deck
CREATE INDEX IF NOT EXISTS idx_cards_deck_id
  ON cards (deck_id);

-- cards: delete all user's cards on account deletion
CREATE INDEX IF NOT EXISTS idx_cards_user_id
  ON cards (user_id);

-- srs_state: primary review query — due cards for a user (ordered by due_date)
CREATE INDEX IF NOT EXISTS idx_srs_user_due
  ON srs_state (user_id, due_date);

-- srs_state: lookup by card (update after review)
CREATE INDEX IF NOT EXISTS idx_srs_card_id
  ON srs_state (card_id);

-- ai_usage: check + increment monthly usage
CREATE INDEX IF NOT EXISTS idx_ai_usage_user_month
  ON ai_usage (user_id, month);

-- ============================================================
-- TRIGGER FUNCTION: auto-update updated_at on any row change
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to tables with updated_at
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_decks_updated_at
  BEFORE UPDATE ON decks
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_cards_updated_at
  BEFORE UPDATE ON cards
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
